In [1]:
#Arrays
import numpy as np
arr = np.array([[0,1,2], [3,4,5]], dtype=np.float32)
print(repr(arr))

array([[0., 1., 2.],
       [3., 4., 5.]], dtype=float32)


In [2]:
#Copying
a = np.array([0,1])
b = np.array([7,9])
c = a
print('Array a: {}'.format(repr(a)))
c[0] = 5
print('Array a: {}'.format(repr(a)))
d = b.copy()
d[0] = 6
print('Array b: {}'.format(repr(a)))


Array a: array([0, 1])
Array a: array([5, 1])
Array b: array([5, 1])


In [3]:
#Casting
arr = np.array([0,1,2])
print(arr.dtype)
arr = arr.astype(np.float32)
print(arr.dtype)



int32
float32


In [4]:
#NaN
arr = np.array([np.nan,1,2])
print(repr(arr))

arr = np.array([np.nan,'abc'])
print(repr(arr))

np.array([np.nan,1,2], dtype=np.int32)



array([nan,  1.,  2.])
array(['nan', 'abc'], dtype='<U32')


ValueError: cannot convert float NaN to integer

In [5]:
#Infinity
print(np.inf > 10000000)
arr = np.array([np.inf, 5])
print(repr(arr))

arr = np.array([-np.inf, 3])
print(repr(arr))

np.array([np.inf, 3], dtype=np.int32)


True
array([inf,  5.])
array([-inf,   3.])


OverflowError: cannot convert float infinity to integer